language: minimal

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov

install:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
  - cp -r tests .release/BM-utils
  - cd .release/BM-utils

before_script:
  - luacheck addon --no-color -q -g --no-self

script:
  - cd tests
  - wget https://raw.githubusercontent.com/Gethe/wow-ui-source/classic/SharedXML/Util.lua
  - lua -lluacov test_utils.lua

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd $TRAVIS_BUILD_DIR
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
