---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anders.
--- DateTime: 07.12.2019 19.47
---
local lu = require('luaunit')

addon = {}
debugstack = debug.traceback
strmatch = string.match

DEFAULT_CHAT_FRAME = {}
function DEFAULT_CHAT_FRAME:AddMessage(...)

end

loadfile('wow_functions.lua')
loadfile('../libs/LibStub/LibStub.lua')()
loadfile('../addon/utils.lua')()
local utils = LibStub('BM-utils-1.0')

_G['test'] = {}
local test = _G['test']

function test:testColorize()
    local text = utils:colorize('Quadduo', 'ff3fbf3f')
    lu.assertEquals(text, '|cff3fbf3fQuadduo|r')
end

function test:testSprintf()
    local text = utils:sprintf('Quad%s', 'duo')
    lu.assertEquals(text, 'Quadduo')
end

function test:testColor_to_rgb()
    local r,g,b = utils:ColorToRGB({ r = 0.25, g = 0.75, b = 0.25 })
    lu.assertEquals(r, 63.75)
    lu.assertEquals(g, 191.25)
    lu.assertEquals(b, 63.75)
end

function test:testGenerateHexColor()
    local hex = utils:GenerateHexColor(63.75, 191.25, 63.75)
    lu.assertEquals(hex, 'ff3fbf3f')
end

function test:testColor_to_hex()
    local hex = utils:ColorToHex({ r = 0.25, g = 0.75, b = 0.25 })
    lu.assertEquals(hex, 'ff3fbf3f')
end

function test:testSplitCharacterString()
    local character, realm = utils:SplitCharacterString('Quadduo-MirageRaceway')
    lu.assertEquals(character, 'Quadduo')
    lu.assertEquals(realm, 'MirageRaceway')
end

os.exit( lu.LuaUnit.run() )

