---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anders.
--- DateTime: 07.12.2019 19.47
---
local lu = require('luaunit')

loadfile('wow_functions.lua')()
loadfile('../libs/LibStub/LibStub.lua')()
loadfile('../addon/utils.lua')()
local utils = LibStub('BM-utils-1.0')

_G['test'] = {}
local test = _G['test']

function test:testDefaultFontColor()
    local _, r, g, b = utils:cprint('test')
    lu.assertEquals(r, 1)
    lu.assertEquals(g, 1)
    lu.assertEquals(b, 1)
    utils:SetDefaultFontColor(0, 0.25, 0.35)
    _, r, g, b = utils:cprint('test')
    lu.assertEquals(r, 0)
    lu.assertEquals(g, 0.25)
    lu.assertEquals(b, 0.35)
end

function test:testSprintf()
    local text = utils:sprintf('Quad%s', 'duo')
    lu.assertEquals(text, 'Quadduo')
end

function test:testColorize()
    local text = utils:colorize('Quadduo', 'ff3fbf3f')
    lu.assertEquals(text, '|cff3fbf3fQuadduo|r')
end

function test:testSprintf()
    local text = utils:sprintf('Quad%s', 'duo')
    lu.assertEquals(text, 'Quadduo')
end

function test:testIsWoWClassic()
    local is_classic = utils:IsWoWClassic()
    lu.assertEquals(is_classic, true)
end

function test:testColor_to_rgb()
    local r,g,b = utils:ColorToRGB({ r = 0.25, g = 0.75, b = 0.25 })
    lu.assertEquals(r, 63.75)
    lu.assertEquals(g, 191.25)
    lu.assertEquals(b, 63.75)
end

function test:testGenerateHexColor()
    local hex = utils:GenerateHexColor(63.75, 191.25, 63.75)
    lu.assertEquals(hex, 'ff3fbf3f')
end

function test:testColor_to_hex()
    local hex = utils:ColorToHex({ r = 0.25, g = 0.75, b = 0.25 })
    lu.assertEquals(hex, 'ff3fbf3f')
end

function test:testSplitCharacterString()
    local character, realm = utils:SplitCharacterString('Quadduo-MirageRaceway')
    lu.assertEquals(character, 'Quadduo')
    lu.assertEquals(realm, 'MirageRaceway')
end

function test:testItemIdFromLink()
    local id = utils:ItemIdFromLink('|cffffffff|Hitem:2318::::::::25:::::::|h[Light Leather]|h|r')
    lu.assertEquals(id, 2318)
end

function test:testItemNameFromLink()
    local id = utils:ItemNameFromLink('|cffffffff|Hitem:2318::::::::25:::::::|h[Light Leather]|h|r')
    lu.assertEquals(id, 'Light Leather')
end

function test:testDifficultyColor()
    local color = utils:DifficultyColor("optimal")
    lu.assertEquals(color, { r = 1.00, g = 0.50, b = 0.25, font = "GameFontNormalLeftOrange" })
    local r, g, b, alpha = utils:DifficultyColor("optimal", true)
    lu.assertEquals(r, 1.00)
    lu.assertEquals(g, 0.50)
    lu.assertEquals(b, 0.25)
    lu.assertEquals(alpha, 255)

end


os.exit( lu.LuaUnit.run() )

