name: Test and package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '*'
    tags:
      - '**'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'cata', 'retail' ]


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get build utils
        uses: actions/checkout@v4
        with:
          repository: Beast-Masters-addons/build_utils
          path: tests/build_utils

      - name: Install lua dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install luarocks
          sudo luarocks install luaunit
          sudo luarocks install luacov
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck addon --no-self

      - name: Build the addon
        uses: BigWigsMods/packager@v2.3.1
        with:
          args: -g ${{ matrix.game_version }} -z -d

      - name: Move libraries
        run: mv .release/BM-utils/libs .

      - name: Download classic UI source
        if: matrix.game_version == 'classic'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic_era'

      - name: Download Wrath Classic UI source
        if: matrix.game_version == 'cata'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic'

      - name: Download retail UI source
        if: matrix.game_version == 'retail'
        uses: actions/checkout@v4
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'live'

      - name: Run tests
        working-directory: ./tests
        run: |
          lua -lluacov test_load.lua
          lua -lluacov test_basic.lua
          lua -lluacov test_character_info.lua
          lua -lluacov test_container.lua
          lua -lluacov test_container_compat.lua
          lua -lluacov test_gettext.lua
          lua -lluacov test_table.lua
          lua -lluacov test_text.lua
          lua -lluacov test_utils.lua
          lua -lluacov test_version.lua
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    needs:
      - test

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.3.1

      - uses: actions/upload-artifact@v4
        with:
          name: BM-utils
          path: .release
