name: Test and package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'classic', 'bcc', 'retail' ]


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get build utils
        uses: actions/checkout@v3
        with:
          repository: Beast-Masters-addons/build_utils
          path: tests/build_utils

      - name: Install lua dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install luarocks
          sudo luarocks install luaunit
          sudo luarocks install luacov
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck addon --no-self

      - name: Download classic UI source
        if: matrix.game_version == 'classic'
        uses: actions/checkout@v3
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic_era'

      - name: Download Burning Crusade Classic UI source
        if: matrix.game_version == 'bcc'
        uses: actions/checkout@v3
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'classic'

      - name: Download retail UI source
        if: matrix.game_version == 'retail'
        uses: actions/checkout@v3
        with:
          repository: Gethe/wow-ui-source
          path: tests/wow-ui-source
          ref: 'live'

      - name: Run tests
        working-directory: ./tests
        run: |
          lua -lluacov test_utils.lua
          lua -lluacov test_version.lua
          lua -lluacov test_gettext.lua
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    needs:
      - test

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.1.0

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.game_version }}
          path: .release
